name: auto-tx-bot

on:
  workflow_dispatch:          # run manually
  schedule:
    - cron: "*/15 * * * *"    # every 15 min; change if you like

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install --no-audit --no-fund           # needs package.json committed

      - name: Send transaction
        run: node src/bot.js  # adjust if your file lives elsewhere
env:
  RPC_URL:           ${{ secrets.RPC_URL }}
  TOKEN_ADDRESS:     ${{ secrets.TOKEN_ADDRESS }}
  TOKEN_DECIMALS:    ${{ secrets.TOKEN_DECIMALS }}
  VALUE_TOKENS:      ${{ secrets.VALUE_TOKENS }}
  TO_ADDRESS:        ${{ secrets.TO_ADDRESS }}
  WALLET_KEYS_JSON:  ${{ secrets.WALLET_KEYS_JSON }}

